
name: Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Fontforge
      run: sudo apt update && sudo apt install fontforge
    - name: Build
      run: sh build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: HuayingMincho
        path: "*.tt*"

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "test-build-01"
        artifacts: |
            *.tt*
            *.7z
        allowUpdates: true
        prerelease: true
        draft: true
        name: "Build Test"
        body: "Test"
        
