
name: Build

on:
  workflow_dispatch
  #push:
   # branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Fontforge
      run: sudo apt install fontforge
    - name: Begin
      run: |
        sh build.sh
        
    - name: Upload release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "test-build-01"
        prerelease: true
        title: Daily Test
        draft: true
        files: |
            *.tt*
            *.7z
            
    - uses: actions/upload-artifact@v3
      with:
        name: HuayingMincho
        path: "*.tt*"


